### ISSUE TITLE
Hardcoded database Credentials in source code

### ISSUE THREAD

**Issue by honeyakshat999** [seyuf/4ChanLike#2]
### Description: 	
During the testing, hard-coded credentials were identified. It is not recommended to store credentials in source-code

#### Affected Resources:
▶	https://github.com/seyuf/4ChanLike/blob/14df3320f2fc0510ce096002088a395321a5cb9a/EsgiRouter/WEB-INF/src/org/esgi/orm/my/ORM.java#L43:L44

#### CVSS Overall Score: 6.6 
Reference link: `https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator?vector=AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:H`
   
#### Business Risk:  
Hardcoded database credentials in source code pose security risks by exposing sensitive information, potentially leading to data breaches and compliance violations. Operational disruptions may occur when credentials need updating, and reputational damage can ensue from breaches, impacting trust and business relationships. Additionally, dependency on individual knowledge and lack of scalability hinder system management and growth.

#### Technical Risk:  
Hardcoding database credentials in source code heightens the risk of unauthorized access, complicates operational tasks like credential updates, and hinders auditing efforts, all of which impede system resilience and scalability.
Remediation: 
▶	Use environment variables to securely provide credentials.
▶	Retrieve credentials from a secure vault or HSM (Hardware Security Module).

### Steps to Reproduce:
1.	Go to the affected resources.
Observe that there are hard-coded secrets in the files.
![image](https://github.com/seyuf/4ChanLike/assets/37788408/1f4fcaf4-3cbb-46fe-a592-8146a02b5c88)
![image](https://github.com/seyuf/4ChanLike/assets/37788408/8d5f3347-d83c-4ad9-ac60-6e428f8dcf34)

**Comment by seyuf** [comment]
Hi @honeyakshat999, 
This was a dummy user/pwd identity. The code is out dated, no there's no real threats here.
Thanks, though.

**Comment by seyuf** [comment]
And for those using this code of course, you should follow [12factor](https://12factor.net/) thus be using env variables.
